### ISSUE TITLE
Cannot find module 'angular2-chartist'

### ISSUE THREAD

**Issue by ajbeaven** [paradox41/angular2-chartist#11]
Many apologies, you'll have to excuse my ignorance with all things Angular2, TypeScript, typings, npm, etc. I'm only a few hours in to my first Angular project and know next to nothing about the aforementioned technologies. 

I seem to be having trouble loading this module. I'm using SystemJS with the following config:

```
(function () {
	var map = {
		// others
		'angular2-chartist': 'node_modules/angular2-chartist/dist',
		'chartist': 'node_modules/chartist/dist'
	};

	var packages = {
		// others
		'angular2-chartist': { main: 'angular2-chartist', defaultExtension: 'js' },
		'chartist': { main: 'chartist', defaultExtension: 'js' }
	};

	var config = {
		map: map,
		packages: packages
	}

	System.config(config);

})(this);
``` 
Now when I try to load the module using the following code in my component, it fails with the build error `Cannot find module 'angular2-chartist'`. 
```
import { ChartistComponent, ChartType, ChartEvent } from 'angular2-chartist';
```
The build error goes away if reference the package like so
```
import { ChartistComponent, ChartType, ChartEvent } from '../../../node_modules/angular2-chartist/src/chartist.component.ts'
```
however then I get the run time error 
`Error loading http://localhost:56580/node_modules/angular2-chartist/src/chartist.component.ts as "../../../node_modules/angular2-chartist/src/chartist.component.ts" from http://localhost:56580/app/components/dashboard/dashboard.component.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) Error: XHR error (404 Not Found)`. 

Funnily enough, if after I start debugging the program (I'm using Visual Studio) by fixing the build error like I mentioned above and then subsequently change to the first method of referencing the package without stopping debugging, everything runs successfully. Upon stopping debugging, I then get that build error again. Perhaps this is typical with these sorts of errors, but as a newbie, it seemed strange enough to mention here.

Again, I'm very new to all of this, but I don't seem to have any of the same problems loading other modules. Please let me know if I'm doing something stupid (highly likely I'm sure!) or if there's any further information I can offer that might assist you.

As a side note, previously even angular2-chartist.js was having issues referencing chartist, however I fixed that by running `typings install dt~chartist --save --global`. Perhaps this should be included in the Installation readme? Or perhaps this is so obvious to those familiar with Angular2 that things like this are not typically mentioned... what do I know?!

**Comment by paradox41** [comment]
Hey there, It doesn't look like you are doing anything (obviously) wrong. Probably the reason it cannot find typings for my module is because [there are none](https://github.com/paradox41/angular2-chartist/blob/master/webpack.config.dist.js#L49-L50). I will try and find a workaround for this ASAP since it is an issue.

In the meantime, if you do something like this: 

```js
const angular2Chartist = require('angular2-chartist')`

const { ChartistComponent, ChartType, ChartEvent } = angular2Chartist;
```

Maybe the error will go away?

**Comment by ajbeaven** [comment]
I get the error `Cannot find name 'require'`. Do I need to import something in order to use `require`?

**Comment by paradox41** [comment]
So I am not all that familiar with SystemJS, but in TypeScript you can `require` a module (just like in Node) and the compiler won't complain about not having typings.

**Comment by paradox41** [comment]
Honestly, I just need to include the typings. I will try and fix that today

**Comment by paradox41** [comment]
Please install 0.6.0 and let me know if that fixes it.

**Comment by ajbeaven** [comment]
After updating to 0.6.0, all is well. Thanks Will!

**Comment by ajbeaven** [comment]
Actually, it seems now I'm getting a run time error: `Cannot read property 'core' of undefined` in universalModuleDefinition as seen here:
![capture](https://cloud.githubusercontent.com/assets/657201/16644730/32525b12-4473-11e6-80d7-97f465c7d039.PNG)

Are there other dependencies I need to include?

**Comment by paradox41** [comment]
Interesting. I will take a look at this later today.

**Comment by paradox41** [comment]
Okay, so after doing some digging, the UMD is correct, you might just have something misconfigured.

Checkout `node_modules/@angular/core/bundles/core.umd.js`: 

```js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('rxjs/Subject'), require('rxjs/observable/PromiseObservable'), require('rxjs/operator/toPromise'), require('rxjs/Observable')) :
        typeof define === 'function' && define.amd ? define(['exports', 'rxjs/Subject', 'rxjs/observable/PromiseObservable', 'rxjs/operator/toPromise', 'rxjs/Observable'], factory) :
            (factory((global.ng = global.ng || {}, global.ng.core = global.ng.core || {}), global.Rx, global.Rx, global.Rx.Observable.prototype, global.Rx));
}(this, function (exports, rxjs_Subject, rxjs_observable_PromiseObservable, rxjs_operator_toPromise, rxjs_Observable) {
```

Specifically this line: 

```js
(factory((global.ng = global.ng || {}, global.ng.core = global.ng.core || {})
```

This maps to the above UMD you linked since:

`root["ng"]["core"] === global.ng.core`

If you can link a plunkr or something, I can try and help debug.

**Comment by ajbeaven** [comment]
Just a stab, I note the footer at the end of that file mentions webpack. Does this need to be installed? `npm install webpack -g`

**Comment by paradox41** [comment]
I personally wouldn't expect webpack to be installed in order for this to
work. That defeats the point of a UMD

**Comment by ajbeaven** [comment]
Ahh, found it - I had a duplicate reference to angular2-chartist.js that was causing this error, probably added when I was playing around trying to get it working initially. Apologies! Everything's working well now with no errors :dancer:

**Comment by paradox41** [comment]
Awesome!
